openapi: 3.0.3
x-stoplight:
  id: d7aclnawwa0g4
info:
  title: Harness NextGen Software Delivery Platform API Reference
  version: '1.0'
  description: This is the Open Api Spec 3 for the Audit Service. This is under active development. Beware of the breaking change with respect to the generated code stub.
  contact:
    email: contact@harness.io
servers:
  - url: 'https://app.harness.io'
    description: Harness host URL.
paths:
  /v1/streaming-destinations:
    parameters: []
    post:
      summary: Create a Streaming Destination
      operationId: create-streaming-destinations
      description: Creates a custom Streaming Destination
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      security:
        - x-api-key: []
      responses:
        '201':
          $ref: '#/components/responses/StreamingDestinationResponse'
      requestBody:
        $ref: '#/components/requestBodies/CreateStreamingDestinationRequest'
      x-internal: true
      tags:
        - Streaming Destinations
    get:
      summary: List Streaming Destinations
      operationId: get-streaming-destinations
      responses:
        '200':
          $ref: '#/components/responses/StreamingDestinationListResponse'
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
        - $ref: '#/components/parameters/PageIndex'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Sort'
        - $ref: '#/components/parameters/Order'
        - $ref: '#/components/parameters/SearchTerm'
        - $ref: '#/components/parameters/Status'
      description: Get list of Streaming Destinations
      security:
        - x-api-key: []
      tags:
        - Streaming Destinations
      x-internal: true
  /v1/streaming-destinations/aggregate:
    get:
      summary: List Streaming Destinations
      operationId: getStreamingDestinationsAggregate
      responses:
        '200':
          $ref: '#/components/responses/StreamingDestinationAggregateListResponse'
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
        - $ref: '#/components/parameters/PageIndex'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Sort'
        - $ref: '#/components/parameters/Order'
        - $ref: '#/components/parameters/SearchTerm'
        - $ref: '#/components/parameters/Status'
      description: Get list of Streaming Destinations
      security:
        - x-api-key: []
      tags:
        - Streaming Destinations
      x-internal: true
  '/v1/streaming-destinations/{streaming-destination}':
    parameters:
      - $ref: '#/components/parameters/StreamingDestinationParam'
    put:
      summary: Update a Streaming Destination
      operationId: update-streaming-destination
      description: Update a Streaming Destination
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      requestBody:
        $ref: '#/components/requestBodies/CreateStreamingDestinationRequest'
      responses:
        '200':
          $ref: '#/components/responses/StreamingDestinationResponse'
      security:
        - x-api-key: []
      tags:
        - Streaming Destinations
      x-internal: true
    delete:
      summary: Delete a Streaming Destination
      operationId: delete-disabled-streaming-destination
      description: Deletes an existing and disabled Streaming Destination
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      security:
        - x-api-key: []
      responses:
        '204':
          $ref: '#/components/responses/StreamingDestinationResponse'
      x-internal: true
      tags:
        - Streaming Destinations
    get:
      summary: Get a Streaming Destination
      operationId: get-streaming-destination
      description: Get a Streaming Destination
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      security:
        - x-api-key: []
      responses:
        '200':
          $ref: '#/components/responses/StreamingDestinationResponse'
      x-internal: true
      tags:
        - Streaming Destinations
  '/v1/streaming-destinations/{streaming-destination}/validate-unique-identifier':
    get:
      summary: Validate Uniqueness of Identifier
      tags:
        - Streaming Destinations
      responses:
        '200':
          $ref: '#/components/responses/StreamingDestinationValidateResponse'
          headers: {}
      operationId: validateUniqueIdentifier
      description: Validate uniqueness of identifier for Streaming Destination
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      security:
        - x-api-key: []
      x-internal: true
    parameters:
      - name: streaming-destination
        in: path
        required: true
        schema:
          type: string
        description: Streaming Destination identifier
  /v1/streaming-destinations/cards:
    get:
      summary: Your GET endpoint
      tags:
        - Streaming Destinations
      responses:
        '200':
          $ref: '#/components/responses/StreamingDestinationCardsResponse'
      operationId: get-streaming-destinations-cards
      x-internal: true
      description: Get the info for cards on streaming destination page
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
  /v1/audits:
    post:
      summary: List Audits
      operationId: post-audits
      responses:
        '200':
          $ref: '#/components/responses/AuditListResponse'
      description: Get list of Audits
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
        - $ref: '#/components/parameters/PageIndex'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Sort'
        - $ref: '#/components/parameters/Order'
      security:
        - x-api-key: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuditFilterPropertiesV1DTO'
        description: This has the filter attributes for listing Audit Events
      tags:
        - Audits
      x-internal: true
components:
  schemas:
    StreamingDestinationStatus:
      title: StreamingDestinationStatus
      x-stoplight:
        id: 6k8zse7tcg5y0
      type: string
      x-extension-1: null
      enum:
        - ACTIVE
        - INACTIVE
      description: Streaming Destination Status enum
      x-internal: false
    StreamingDestinationDTO:
      title: StreamingDestinationDTO
      x-stoplight:
        id: ooye81jxpefty
      type: object
      description: Streaming Destination model
      properties:
        identifier:
          type: string
          description: Streaming Destination identifier
        name:
          type: string
          description: Streaming Destination name
        status:
          $ref: '#/components/schemas/StreamingDestinationStatus'
        connector_ref:
          type: string
          description: Streaming Destination scoped connector reference identifier
        spec:
          $ref: '#/components/schemas/StreamingDestinationSpecDTO'
        description:
          type: string
          maxLength: 1024
          description: Description for Streaming Destination
        tags:
          type: object
          additionalProperties:
            type: string
          maxProperties: 128
          description: Tags for Streaming Destination
      required:
        - identifier
        - name
        - status
        - connector_ref
        - spec
    Connector:
      type: object
      x-internal: true
      properties:
        name:
          type: string
          description: Connector name
          pattern: '^[0-9a-zA-Z-_ ]{0,127}$'
        identifier:
          type: string
          minLength: 1
          pattern: '^[a-zA-Z_][0-9a-zA-Z_$]{0,127}$'
          description: Connector identifier
          maxLength: 128
        description:
          type: string
          description: Connector description
        org:
          type: string
          description: Organization identifier for connector
          pattern: '^[a-zA-Z_][0-9a-zA-Z-_ ]{0,127}$'
        project:
          type: string
          description: Project identifier for connector
          pattern: '^[a-zA-Z_][0-9a-zA-Z-_ ]{0,127}$'
        tags:
          type: object
          additionalProperties:
            type: string
          description: Connector tags
      required:
        - name
        - identifier
    StreamingDestinationSpecDTO:
      title: StreamingDestinationSpecDTO
      x-stoplight:
        id: s4mguy0st7rtt
      type: object
      discriminator:
        propertyName: type
        mapping:
          AWS_S3: '#/components/schemas/AwsS3StreamingDestinationSpecDTO'
      properties:
        type:
          type: string
          enum:
            - AWS_S3
          description: This specifies the type of Streaming Destination
      required:
        - type
      description: ''
    AwsS3StreamingDestinationSpecDTO:
      allOf:
        - $ref: '#/components/schemas/StreamingDestinationSpecDTO'
        - type: object
          properties:
            bucket:
              type: string
              description: The bucket in AWS S3 where audit records are to be written
          required:
            - bucket
      title: AwsS3StreamingDestinationSpecDTO
      description: AwsS3 Streaming Destination model
      x-discriminator-value: AWS_S3
    StreamingDestinationResponse:
      title: StreamingDestinationResponse
      x-stoplight:
        id: rulrehs9nk5a3
      type: object
      description: Streaming Destination response model
      properties:
        streaming_destination:
          $ref: '#/components/schemas/StreamingDestinationDTO'
        created:
          type: integer
          format: int64
          description: Created time of the Streaming Destination
        updated:
          type: integer
          format: int64
          description: Last updated time of the Streaming Destination
        status_updated:
          type: integer
          format: int64
          description: Last updated time of the Streaming Destination status
      required:
        - streaming_destination
    StreamingDestinationCards:
      title: StreamingDestinationCards
      x-stoplight:
        id: 1dw4ls5voxwl2
      type: object
      description: Streaming Destination Cards model
      properties:
        countByStatusCard:
          type: array
          items:
            $ref: '#/components/schemas/StatusWiseCount'
        lastStreamedCard:
          $ref: '#/components/schemas/LastStreamedCard'
        failureInfoCard:
          $ref: '#/components/schemas/FailureInfoCard'
    StatusWiseCount:
      title: StatusWiseCount
      x-stoplight:
        id: 2ad155c277a03
      type: object
      description: Streaming Destination count by status card
      properties:
        status:
          $ref: '#/components/schemas/StreamingDestinationStatus'
        count:
          type: integer
          description: Number of streaming destinations at the status
    LastStreamedCard:
      title: LastStreamedInfo
      x-stoplight:
        id: a35601e416967
      type: object
      description: Info about last successfull streaming attempt
      properties:
        lastStreamedAt:
          type: integer
          format: int64
          description: Timestamp of last successfull streaming attempt
    FailureInfoCard:
      title: FailureCard
      x-stoplight:
        id: a2d05f2010784
      type: object
      description: Info about failure in streaming attempt
      properties:
        count:
          type: integer
          description: Number of streaming destinations that have failure
          format: int64
    StreamingDestinationAggregateDTO:
      title: StreamingDestinationAggregateDTO
      x-stoplight:
        id: chl0l737sfwea
      type: object
      description: Streaming Destination Aggregate DTO
      properties:
        streaming_destination:
          $ref: '#/components/schemas/StreamingDestinationDTO'
        connector_info:
          $ref: '#/components/schemas/Connector'
        streaming_details:
          $ref: '#/components/schemas/StreamingDetails'
      required:
        - streaming_destination
        - connector_info
    StreamingDetails:
      title: StreamingDetails
      x-stoplight:
        id: 505pv39rdv4z1
      type: object
      properties:
        status:
          type: string
          description: Status of the batch
          enum:
            - READY
            - IN_PROGRESS
            - SUCCESS
            - FAILED
        last_streamed_at:
          type: integer
          format: int64
        error_message:
          type: string
      description: Details of the last streamed batch
      x-internal: true
    ResourceScopeDTO:
      title: ResourceScopeDTO
      x-stoplight:
        id: 4pz290lmuwtl3
      type: object
      description: This has scope details for the resource defined in Harness.
      properties:
        account_identifier:
          type: string
          description: Identifier of Account
        org_identifier:
          type: string
          description: Identifier of Organization
        project_identifier:
          type: string
          description: Identifier of Project
        labels:
          type: object
          additionalProperties:
            type: string
    ResourceDTO:
      title: ResourceDTO
      x-stoplight:
        id: 2r7wy11v8scql
      type: object
      description: This contains info about Resource saved as a part of Audit Event
      properties:
        type:
          type: string
        identifier:
          type: string
        labels:
          type: object
          additionalProperties:
            type: string
    AuditFilterPropertiesV1DTO:
      title: AuditFilterPropertiesV1DTO
      x-stoplight:
        id: hrclq6ndh1ymg
      type: object
      description: Properties of the Filter entity defined in Harness.
      properties:
        filter_type:
          $ref: '#/components/schemas/FilterType'
        tags:
          type: object
          additionalProperties:
            type: string
          maxProperties: 128
          description: tags
        start_time:
          type: integer
          format: int64
          description: Used to specify a start time for retrieving Audit events that occurred at or after the time indicated.
        end_time:
          type: integer
          format: int64
          description: Used to specify the end time for retrieving Audit events that occurred at or before the time indicated.
        modules:
          type: array
          description: List of Module Types
          items:
            $ref: '#/components/schemas/ModuleType'
        actions:
          type: array
          description: List of Actions
          items:
            $ref: '#/components/schemas/Action'
        resources:
          type: array
          description: List of Resources
          items:
            $ref: '#/components/schemas/ResourceDTO'
        scopes:
          type: array
          description: List of Resource Scopes
          items:
            $ref: '#/components/schemas/ResourceScopeDTO'
        principals:
          type: array
          items:
            $ref: '#/components/schemas/Principal'
        static_filter:
          type: array
          items:
            $ref: '#/components/schemas/StaticAuditFilter'
        environments:
          type: array
          items:
            $ref: '#/components/schemas/Environment'
    StaticAuditFilter:
      title: StaticAuditFilter
      x-stoplight:
        id: mdul5d1wgfhez
      type: string
      enum:
        - SYSTEM_EVENTS
        - LOGIN_EVENTS
        - ENTITY_CHANGE_EVENTS
        - RUNTIME_EVENTS
    ModuleType:
      title: ModuleType
      x-stoplight:
        id: xjqf65bl7w788
      type: string
      description: Type of Modules
      enum:
        - CD
        - CI
        - CV
        - CF
        - CE
        - STO
        - CORE
        - PMS
        - TEMPLATESERVICE
        - GOVERNANCE
        - CHAOS
        - CET
    Action:
      title: Action
      x-stoplight:
        id: bzquds8sspg1q
      type: string
      enum:
        - CREATE
        - UPDATE
        - RESTORE
        - DELETE
        - FORCE_DELETE
        - UPSERT
        - INVITE
        - RESEND_INVITE
        - REVOKE_INVITE
        - ADD_COLLABORATOR
        - REMOVE_COLLABORATOR
        - CREATE_TOKEN
        - REVOKE_TOKEN
        - LOGIN
        - LOGIN2FA
        - UNSUCCESSFUL_LOGIN
        - ERROR_BUDGET_RESET
    Principal:
      title: Principal
      x-stoplight:
        id: tj7q0qb2zdnyw
      type: object
      properties:
        identifier:
          type: string
        type:
          $ref: '#/components/schemas/PrincipalType'
    PrincipalType:
      title: PrincipalType
      x-stoplight:
        id: fxz45g9sxt8f2
      type: string
      enum:
        - USER
        - SYSTEM
        - API_KEY
        - SERVICE_ACCOUNT
    Environment:
      title: Environment
      x-stoplight:
        id: jmpmivgkftb1v
      type: object
      properties:
        identifier:
          type: string
        type:
          $ref: '#/components/schemas/EnvironmentType'
    EnvironmentType:
      title: EnvironmentType
      x-stoplight:
        id: ihuiok9k1qcmz
      type: string
      enum:
        - PreProduction
        - Production
    FilterType:
      title: FilterType
      x-stoplight:
        id: nvm8xs2of7vf8
      type: string
      enum:
        - CONNECTOR
        - DELEGATEPROFILE
        - DELEGATE
        - PIPELINESETUP
        - PIPELINEEXECUTION
        - DEPLOYMENT
        - AUDIT
        - TEMPLATE
        - ENVIRONMENTGROUP
        - FILESTORE
        - CCMRECOMMENDATION
        - ANOMALY
        - ENVIRONMENT
        - RULEEXECUTION
    AuditEventDTO:
      title: AuditEventDTO
      x-stoplight:
        id: mxditpr8jr7lh
      type: object
      properties:
        audit_id:
          type: string
        insert_id:
          type: string
        resource_scope:
          $ref: '#/components/schemas/ResourceScopeDTO'
        timestamp:
          type: integer
        module:
          $ref: '#/components/schemas/ModuleType'
        http_request_info:
          $ref: '#/components/schemas/HttpRequestInfo'
        request_metadata:
          $ref: '#/components/schemas/RequestMetadata'
        authentication_info:
          $ref: '#/components/schemas/AuthenticationInfoDTO'
        environment:
          $ref: '#/components/schemas/Environment'
        resource:
          $ref: '#/components/schemas/ResourceDTO'
        yaml_diff_record:
          $ref: '#/components/schemas/YamlDiffRecordDTO'
        action:
          $ref: '#/components/schemas/Action'
        internal_info:
          type: object
          additionalProperties:
            type: string
    HttpRequestInfo:
      title: HttpRequestInfo
      x-stoplight:
        id: xv4gl47om7rva
      type: object
      properties:
        request_method:
          type: string
    RequestMetadata:
      title: RequestMetadata
      x-stoplight:
        id: ga39sbthmsnqw
      type: object
      properties:
        client_ip:
          type: string
    AuthenticationInfoDTO:
      title: AuthenticationInfoDTO
      x-stoplight:
        id: vbhi03cpej4ej
      type: object
      properties:
        principal:
          $ref: '#/components/schemas/Principal'
        labels:
          type: string
    YamlDiffRecordDTO:
      title: YamlDiffRecordDTO
      x-stoplight:
        id: 9t10m54ew32zz
      type: object
      description: This has the YAML Difference of the record.
      properties:
        old_yaml:
          type: string
          description: Previous YAML version
        new_yaml:
          type: string
          description: Current YAML version
  securitySchemes:
    x-api-key:
      name: x-api-key
      type: apiKey
      in: header
      description: API key is a token provided while making the API calls. This is used to authenticate the client at the exposed endpoint.
  parameters:
    Limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        default: 30
        maximum: 100
      description: 'Pagination: Number of items to return.'
    PageIndex:
      name: page
      in: query
      required: false
      schema:
        type: integer
        default: 0
      description: 'Pagination page number strategy: Specify the page number within the paginated collection related to the number of items on each page.'
    SearchTerm:
      name: search_term
      in: query
      required: false
      schema:
        type: string
      description: This would be used to filter resources having attributes matching the search term.
    AccountHeader:
      name: Harness-Account
      in: header
      required: false
      schema:
        type: string
      description: 'Identifier field of the account the resource is scoped to. This is required for Authorization methods other than the x-api-key header. If you are using the x-api-key header, this can be skipped.'
    Sort:
      name: sort
      in: query
      required: false
      schema:
        type: string
        enum:
          - identifier
          - name
          - created
          - updated
      description: Parameter on the basis of which sorting is done.
    Order:
      name: order
      in: query
      required: false
      schema:
        type: string
        enum:
          - ASC
          - DESC
      description: Order on the basis of which sorting is done.
    Status:
      name: status
      in: query
      required: false
      schema:
        type: string
      description: Status of the Streaming Destination
    StreamingDestinationParam:
      name: streaming-destination
      in: path
      required: true
      schema:
        type: string
      description: Streaming Destination identifier
  responses:
    StreamingDestinationResponse:
      description: Streaming Destination response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StreamingDestinationResponse'
          examples:
            example-streaming-destination-response:
              value:
                streaming_destination:
                  identifier: example_destination
                  name: example desitnation name
                  status: ACTIVE
                  connector_ref: account.example_connector
                  spec:
                    type: AWS_S3
                    bucket: example_bucket
                created: 1670304106000
                update: 1670304106000
    StreamingDestinationListResponse:
      description: Streaming Destination list response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/StreamingDestinationResponse'
          examples:
            example-list-streaming-destination-response:
              value:
                - streaming_destination:
                    identifier: example_destination
                    name: example desitnation name
                    status: ACTIVE
                    connector_ref: account.example_connector
                    spec:
                      type: AWS_S3
                      bucket: example_bucket
                  created: 1670304106000
                  update: 1670304106000
      headers:
        X-Total-Elements:
          schema:
            type: integer
          description: Total number of elements returned in Paginated response.
        X-Page-Number:
          schema:
            type: integer
          description: Page number in Paginated response.
        X-Page-Size:
          schema:
            type: integer
          description: Maximum page size in Paginated response.
    StreamingDestinationValidateResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: boolean
            description: It returns true if the Identifier is unique and false if the Identifier is not unique
    StreamingDestinationCardsResponse:
      description: Streaming Destination cards response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StreamingDestinationCards'
    StreamingDestinationAggregateListResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/StreamingDestinationAggregateDTO'
      headers:
        X-Total-Elements:
          schema:
            type: integer
          description: Total number of elements returned in Paginated response.
        X-Page-Number:
          schema:
            type: integer
          description: Page number in Paginated response.
        X-Page-Size:
          schema:
            type: integer
          description: Maximum page size in Paginated response.
    AuditListResponse:
      description: ''
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/AuditEventDTO'
      headers:
        X-Total-Elements:
          schema:
            type: integer
          description: Total number of elements returned in Paginated response.
        X-Page-Number:
          schema:
            type: integer
          description: Page number in Paginated response.
        X-Page-Size:
          schema:
            type: integer
          description: Maximum page size in Paginated response.
  requestBodies:
    CreateStreamingDestinationRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StreamingDestinationDTO'
          examples:
            example-aws-s3-stream-destination-request:
              value:
                identifier: example_destination
                name: example destination name
                status: ACTIVE
                connector_ref: account.example_aws_connector
                spec:
                  type: AWS_S3
                  bucket: example_bucket
      description: Streaming Destination request body
tags:
  - name: Streaming Destinations
    description: This contains APIs for Streaming Destinations.
